move compile test to own dir; check c++11 early

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,19 +4,9 @@ CXXFLAGS=$(${R_HOME}/bin/R CMD config CXXFLAGS)
 CPPFLAGS=$(${R_HOME}/bin/R CMD config CPPFLAGS)
 
 if [ -z "$CLUSTERMQ_USE_SYSTEM_LIBZMQ" ]; then
-cat <<EOF >libzmq_test.c
-#include <zmq.h>
-int main() {
-    #if defined(ZMQ_BUILD_DRAFT_API) && ZMQ_VERSION >= ZMQ_MAKE_VERSION(4, 3, 0)
-    return 0;
-    #endif
-    return 1;
-}
-EOF
-
-  if $(cc -o libzmq_test libzmq_test.c $(pkg-config --cflags --libs libzmq) >/dev/null 2>&1); then
+  if $(cc -o test_libzmq src/util/test_libzmq.c $(pkg-config --cflags --libs libzmq) >/dev/null 2>&1); then
     echo "* system has libzmq -> linking system library"
-    if $(./libzmq_test 2>/dev/null); then
+    if $(./test_libzmq 2>/dev/null); then
       echo "* libzmq has DRAFT API -> enabling crash monitor feature"
       CLUSTERMQ_USE_SYSTEM_LIBZMQ=1
     else
@@ -27,14 +17,20 @@ EOF
     echo "* no system libzmq found -> using bundled libzmq"
     CLUSTERMQ_USE_SYSTEM_LIBZMQ=0
   fi
-  rm -f libzmq_test.c libzmq_test
+  rm -f test_libzmq
 fi
+
+if ! $(cc --std=c++11 -o test_cpp11 src/util/test_cpp11.cpp >/dev/null 2>&1); then
+  echo "ERROR: compiler needs full c++11 support (gcc>=5, clang>=3.3) -> check 'cc --version'"
+  exit 1
+fi
+rm -f test_cpp11
 
 if [ "$CLUSTERMQ_USE_SYSTEM_LIBZMQ" -eq "0" ]; then
   PKG_CFLAGS="-DZMQ_STATIC -DZMQ_BUILD_DRAFT_API=1 -fPIC -Ilibzmq/include -Icppzmq"
   PKG_LIBS="libzmq/src/.libs/libzmq.a"
 
-  ./src/patch_libzmq.sh
+  ./src/util/patch_libzmq.sh
 
   if [ ! -f src/libzmq/src/.libs/libzmq.a ]; then
     cd src/libzmq
